export const CAMPAIGN_JOURNEY_TABLE_NAME = 'campaignjourney';
export const CAMPAIGN_JOURNEY_REPOSITORY = 'CAMPAIGN_JOURNEY_REPOSITORY';
export const CAMPAIGN_SERVICE = 'CAMPAIGN_SERVICE';
export const CAMPAIGN_JOURNEY_SERVICE = 'CAMPAIGN_JOURNEY_SERVICE';
