export enum REPORT_CONDITION {
  GOOD = 'GOOD',
  BAD = 'BAD',
}

export enum REPORT_CATEGORY {
  ZEBRA_CROSS = 'ZEBRA_CROSS',
  SIDEWALK = 'SIDEWALK',
  PELICAN_CROSSING = 'PELICAN_CROSSING',
  OTHER = 'OTHER',
}

export const GEOHASH_PRECISSION = 7;
